config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  get 'welcome' => 'welcome#index'
    controller :sessions do
      get 'login' => :new
      post 'login' => :create
      get 'welcome' => :create
      delete 'logout' => :destroy
  end

  get 'admin/index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :customers
  resources :pictures

  resources :intersections do
    resources :pictures
  end

  resources :paths

  resources :locations do
    resources :pictures
  end

  resources :users do
    resources :locations
  end

  get 'welcome/index'

  root 'sessions#new'

end

app/models/customer.rb
require 'digest/sha2'

class Customer < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password
  validate :password_must_be_present
  after_destroy :ensure_an_admin_remains

  def Customer.authenticate(name, password)
    if customer = find_by_name(name)
      if customer.hashed_password == encrypt_password(password, customer.salt)
        customer
      end
    end
  end

  def Customer.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password +"wibble"+ salt)
  end

  def password=(password)
    @password = password
    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end

  private

  def password_must_be_present
    errors.add(:password, "Missing password") unless self.hashed_password.present?
  end

  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end

  def ensure_an_admin_remains
    if Customer.count.zero?
      raise "Can't delete last user"
    end
  end

end

app/models/intersection.rb
class Intersection < ActiveRecord::Base
  has_many:pictures
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to:users
  has_many:pictures
end

app/models/path.rb
class Path < ActiveRecord::Base
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to:location
  belongs_to:intersection
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  has_many:locations

  validates :name, :pressence => true, :uniqueness => true

  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password

  validate :password_must_be_present

  private

  def password_must_be_present
    errors.add(:password, "Missing password") unless password.present?
  end

  def User.encrpyt_password(password, user_id)
    Digest::SHA2.hexdigest(password + "wibble" + user_id)
  end

  def generate_user_id
    self.user_id = self.object_id.to_s + rand.to_s
  end

  # 'password' is a virtual attribute
  def password=(password)
    @password = password

    if password.present?
      generate_user_id
      self.password = self.class.encrpyt_password(password, user_id)
    end
  end

  def User.authenticate(name, password)
    if user = find_by_name(name)
      if user.password == encrpyt_password(password, user.user_id)
        user
      end
    end
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_locations = Location.count
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.order(:name)
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    respond_to do |format|
      if @customer.save
        format.html { redirect_to(customers_url,
          :notice => "Customer #{@customer.name} was successfully created.") }
          format.xml { render :xml => @customer, :status => :created, :location => @customer }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])
    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to(customers_url, :notice => "Customer #{@customer.name} was successfully updated.") }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @customer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    begin
      @customer.destroy
      flash[:notice] = "User #{@customer.name} deleted"
    rescue Exception => e
        flash[:notice] = e.message
    end
    respond_to do |format|
      format.html { redirect_to customers_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :password, :password_confirmation)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  before_filter :administrator
  def index
    @total_locations = Location.count
  end

  protected
    def administrator
      unless Administrator.find_by_id(session[:id]) && Customer.find_by_id(session[:id])
        redirect_to
    end
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

  def delete
  end

  def edit
  end


  def create
    @user = User.new(params[:user])

    repsond_to do |format|
      if @user.save
        format.html {redirect_to(users_url, :notice => "User #{@user.name} was successfully created.")}
        format.xml {render :xml => @user, :status => :created, :location => @user}
      else
        format.html {render :action => "new"}
        format.xml {render :xml => @user.errors, :status => :unprocessable_entity}
      end
    end
  end

  def updated
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html {redirect_to(users_url, :notice => "User #{@user.name} was successfully updated.")}
        format.xml {head :ok}
      else
        format.html {render :action => "edit"}
        format.xml {render :xml => @user.errors, :status => :unprocessable_entity}
      end
    end
  end

  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html #index.html.erb
      format.xml {render :xml => @users}
    end
  end

end

app/controllers/welcome_controller.rb
require './lib/map.rb'

class WelcomeController < ApplicationController

  def initialize
    @map = CampusMap.new()
    @map.load_buildings("./lib/buildings.txt")
    @map.load_paths("./lib/paths.txt")
    name_list = @map.get_all_nodes_name
    @notes = {}
    name_list.each do |name|
      @notes[name] = name
    end
  end

  def index
    if params[:start] != nil && params[:end] != nil
      startP = @map.get_node_id(params[:start])
      endP = @map.get_node_id(params[:end])
      @result = @map.solve(startP, endP).html_safe
    end
  end


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/intersections_helper.rb
module IntersectionsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/paths_helper.rb
module PathsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/_form.html.erb
<div class="depot_form" >
  <%= form_for @customer do |f| %>
    <% if @customer.errors.any? %>
      <div id="error_explanation" >
        <h2><%= pluralize(@customer.errors.count, "error") %>
          prohibited this user from being saved:</h2>
          <ul>
          <% @customer.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
      </div>
    <% end %>

    <fieldset>
      <legend>Enter Customer Details</legend>
      <div>
        <%= f.label :name %>:
        <%= f.text_field :name, :size => 40 %>
      </div>

      <div>
        <%= f.label :password, 'Password' %>:
        <%= f.password_field :password, :size => 40 %>
      </div>

      <div>
        <%= f.label :password_confirmation, 'Confirm' %>:
        <%= f.password_field :password_confirmation, :size => 40 %>
      </div>

      <div>
        <%= f.submit %>
      </div>

    </fieldset>

  <% end %>
</div>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>
  <% if notice %>
    <p id="notice" ><%= notice %></p>
  <% end %>

  <table>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.name %></td>
      <td><%= link_to 'Show', customer %></td>
      <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
      <td><%= link_to 'Destroy', customer, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>
<br />
<%= link_to 'New customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Hashed password:</strong>
  <%= @customer.hashed_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @customer.salt %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>